#!/usr/bin/env node
// apply-fix.js — Component 6: Safe Fix Applier
// Applies a documentation fix generated by Component 5, but ONLY after
// explicit human approval. No API calls, no git operations.
// No external dependencies. Requires Node.js.

const fs = require("fs");
const path = require("path");

// ---------------------------------------------------------------------------
// 1. Read a file safely, returning content or null on failure.
// ---------------------------------------------------------------------------
function readFileSafe(filePath) {
  try {
    return fs.readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// 2. Normalize line endings to \n for comparison, then locate currentText.
//
//    Returns:
//      { found: false }              → not found at all
//      { found: true, count: 0 }     → impossible, but defensive
//      { found: true, count: 1, index: number, originalSnippet: string }
//      { found: true, count: N }     → ambiguous (N > 1)
//
//    The index is the character offset within the NORMALIZED content.
//    To get the position in the original file, we account for \r\n → \n
//    differences.
// ---------------------------------------------------------------------------
function locateText(fileContent, searchText) {
  // Normalize both to \n for reliable comparison
  const normalizedFile = fileContent.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  const normalizedSearch = searchText.replace(/\r\n/g, "\n").replace(/\r/g, "\n");

  // Count occurrences
  let count = 0;
  let searchFrom = 0;
  let firstIndex = -1;

  while (true) {
    const idx = normalizedFile.indexOf(normalizedSearch, searchFrom);
    if (idx === -1) break;
    if (firstIndex === -1) firstIndex = idx;
    count++;
    searchFrom = idx + normalizedSearch.length;
  }

  if (count === 0) {
    return { found: false, count: 0 };
  }

  if (count > 1) {
    return { found: true, count };
  }

  // Exactly one match — extract the original (with \r\n) snippet
  // by finding the same range in the original content
  const originalFile = fileContent;
  const originalNormalized = originalFile.replace(/\r\n/g, "\n").replace(/\r/g, "\n");

  // Map normalized index back to original index
  let originalIndex = 0;
  let normalizedIndex = 0;
  while (normalizedIndex < firstIndex && originalIndex < originalFile.length) {
    if (originalFile[originalIndex] === "\r" && originalFile[originalIndex + 1] === "\n") {
      // This \r\n maps to a single \n in normalized — advance both
      originalIndex += 2;
      normalizedIndex += 1;
    } else {
      originalIndex++;
      normalizedIndex++;
    }
  }

  // Similarly map the end of the search text
  const searchLen = normalizedSearch.length;
  let endOriginal = originalIndex;
  let endNormalized = normalizedIndex;
  while (endNormalized < normalizedIndex + searchLen && endOriginal < originalFile.length) {
    if (originalFile[endOriginal] === "\r" && originalFile[endOriginal + 1] === "\n") {
      endOriginal += 2;
      endNormalized += 1;
    } else {
      endOriginal++;
      endNormalized++;
    }
  }

  const originalSnippet = originalFile.slice(originalIndex, endOriginal);

  return {
    found: true,
    count: 1,
    originalIndex,
    originalLength: endOriginal - originalIndex,
    originalSnippet,
  };
}

// ---------------------------------------------------------------------------
// 3. Display the proposed change for human review.
// ---------------------------------------------------------------------------
function displayChange(fix) {
  console.log("=== Proposed Documentation Fix ===\n");
  console.log(`File:    ${fix.file}`);
  console.log(`Section: ${fix.section}\n`);

  console.log("--- Current text ---");
  console.log(fix.currentText);
  console.log("");

  console.log("--- Proposed text ---");
  console.log(fix.proposedText);
  console.log("");
}

// ---------------------------------------------------------------------------
// 4. Prompt the user for explicit confirmation.
//    Returns true if the user enters 'y' or 'Y', false otherwise.
// ---------------------------------------------------------------------------
function askForConfirmation() {
  return new Promise((resolve) => {
    process.stdout.write("Apply this fix? (y/n): ");
    process.stdin.setEncoding("utf-8");
    process.stdin.once("data", (data) => {
      const answer = data.trim().toLowerCase();
      resolve(answer === "y" || answer === "yes");
    });
  });
}

// ---------------------------------------------------------------------------
// 5. Apply a single fix to the file.
//
//    SAFETY CHECKS:
//    a) currentText must exist in the file
//    b) currentText must appear exactly once
//    c) User must explicitly approve
//
//    After replacement, writes the file back preserving original line endings.
// ---------------------------------------------------------------------------
async function applyFix(fix) {
  const { file, section, currentText, proposedText } = fix;

  // Step 1: Read the actual documentation file
  const fileContent = readFileSafe(file);
  if (fileContent === null) {
    console.error(`ERROR: Cannot read file: ${file}`);
    console.error("The file may not exist or may not be accessible.");
    return { applied: false, reason: "file_not_found" };
  }

  // Step 2 & 3: Locate currentText and verify exact match
  const locate = locateText(fileContent, currentText);

  if (!locate.found) {
    console.error("ERROR: currentText was NOT found in the documentation file.");
    console.error("");
    console.error("This means the documentation has changed since the fix was generated.");
    console.error("Human review is required. Re-run the pipeline to regenerate the fix.");
    return { applied: false, reason: "text_not_found" };
  }

  if (locate.count > 1) {
    console.error(`ERROR: currentText appears ${locate.count} times in the file.`);
    console.error("");
    console.error("The target is ambiguous. Human review is required to disambiguate.");
    return { applied: false, reason: "ambiguous_match" };
  }

  // Step 4: Display the change
  displayChange(fix);

  // Step 5: Ask for explicit confirmation
  const approved = await askForConfirmation();

  if (!approved) {
    console.log("\nFix NOT applied. File left unchanged.");
    return { applied: false, reason: "user_rejected" };
  }

  // Step 6: Apply the replacement
  // We work with the original content and replace the exact matched snippet
  const before = fileContent.slice(0, locate.originalIndex);
  const after = fileContent.slice(locate.originalIndex + locate.originalLength);
  const newContent = before + proposedText + after;

  // Step 7: Write the file back
  fs.writeFileSync(file, newContent, "utf-8");

  // Step 8: Print success and resulting section
  console.log("\n✓ Fix applied successfully.\n");

  // Show the resulting section
  console.log("--- Resulting documentation section ---");
  console.log(proposedText);
  console.log("");

  return { applied: true, file, section };
}

// ---------------------------------------------------------------------------
// 6. Entry point: standalone test mode or JSON file input.
//    The input JSON should contain: { file, section, currentText, proposedText }
//    or an array of such objects.
// ---------------------------------------------------------------------------
async function main() {
  let fixes;

  if (process.argv[2]) {
    // Load input from a JSON file
    try {
      const raw = JSON.parse(fs.readFileSync(process.argv[2], "utf-8"));
      fixes = Array.isArray(raw) ? raw : [raw];
    } catch (e) {
      console.error(`Error reading input file: ${e.message}`);
      process.exit(1);
    }
  } else {
    // Built-in test case matching the existing repo's login() example
    fixes = [
      {
        file: "docs/authentication.md",
        section: "Login",
        currentText:
          "## Login\r\n" +
          "\r\n" +
          "The login function accepts a username and password.\r\n" +
          "\r\n" +
          "### Usage\r\n" +
          "\r\n" +
          "```js\r\n" +
          "login(username, password)",
        proposedText:
          "## Login\r\n" +
          "\r\n" +
          "The login function accepts an email, password, and a remember-me flag.\r\n" +
          "\r\n" +
          "### Usage\r\n" +
          "\r\n" +
          "```js\r\n" +
          "login(email, password, rememberMe)",
      },
    ];
  }

  console.log(`Processing ${fixes.length} fix(es)...\n`);

  let applied = 0;
  let skipped = 0;

  for (let i = 0; i < fixes.length; i++) {
    if (fixes.length > 1) {
      console.log(`\n--- Fix ${i + 1} of ${fixes.length} ---\n`);
    }

    const result = await applyFix(fixes[i]);
    if (result.applied) {
      applied++;
    } else {
      skipped++;
    }
  }

  // Summary
  console.log("=== Summary ===");
  console.log(`Applied: ${applied}`);
  console.log(`Skipped: ${skipped}`);
  console.log("");
  console.log("No commits were made. No files other than the target were modified.");
}

main();
